server:
  port: 78
  ssl:
    enabled: false
    certificate: /etc/letsencrypt/live/api.teda.uz/fullchain.pem
    certificate-private-key: /etc/letsencrypt/live/api.teda.uz/privkey.pem
spring:
  datasource:
    #    url: jdbc:postgresql://185.185.80.245/eventSystems
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 977515747
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
page:
  size: 20
jwt:
  secretKey: turgun1970
  expireDate: 864000000
debug: false
company:
  department:
    id: 1